### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by faberglas** [bmw9t/introduction-to-text-analysis#100]
One word too many, I included the italicized words.

This is a book about reading and technology, but not quite in the same way as described above. Rather than reading _with_ ~~about~~ technology, we are going to discuss how we might read _through_ technology. It’s not just that we now have access to books, newspapers and magazines online, it’s also that we have access to so much more:

https://bmw9t.gitbooks.io/introduction-to-text-analysis/content/issues/why-read-with-a-computer.html

**Comment by walshbr** [comment]
Thanks @faberglas - I've updated the text. This repo is actually a legacy / archive repository from before we migrated the coursebook to a more sustainable platform. But that particular typo remained. I just took care of it over on the other repo. Thanks for reading!
