### ISSUE TITLE
Review How Computer's Read

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#26]
Check out that lesson, which i just drafted. might benefit from shifting some of the examples to be disciplinary. Any other thoughts/explanations welcome!

**Comment by sehorowitz** [comment]
ok, i added two new paragraphs at the beginning (and slightly modified the one beginning "In the first case, I might be responding with a number of movies that I had seen.") check it out!

**Comment by walshbr** [comment]
Awesome - thanks!
