### ISSUE TITLE
Voyant Part One - review

### ISSUE THREAD

**Issue by sehorowitz** [bmw9t/introduction-to-text-analysis#28]
Take a look at what I came up with for this article (whoa, that's a lot of prepositions in a row). Beyond fixing a typo, I started making changes beginning with the paragraph below the last String of Pearls word cloud (the paragraph starting with "Just like the stopword list can be used to adjust...")

**Comment by walshbr** [comment]
Looks great to me! I just cleaned up the end where some of my notes were.
