### ISSUE TITLE
Distant Reading

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#37]
Drafted! Check it out! I worry that I was spinning my wheels a little bit / covering things that were covered elsewhere. But I think it could be useful for them. Anything you might want expanded on let me know. And as always feel free to add anything you want.

**Comment by sehorowitz** [comment]
looks good! i just did some editing where there seemed to be repetition or tried to add some stuff for clarity. if i took out anything you love dearly, we can add it back in.
