### ISSUE TITLE
Voyant Part Two - review

### ISSUE THREAD

**Issue by sehorowitz** [bmw9t/introduction-to-text-analysis#40]
ok, I did some work on the Voyant Part II article; some light editing and added some stuff on how one might interpret collocation data and the graph of collocations over the course of the novel. I have no idea if i'm right - but neither will the students! anyway, check it over and see if it makes sense to you.

**Comment by walshbr** [comment]
Love it. Like any of these arguments, I think one would want more evidence to be able to make some of them. I think they're totally fine for demonstrations.
