### ISSUE TITLE
review bag of words lesson

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#42]
take a look at bag of words and see what you think. i decided to break apart topic modeling into two pieces - the epistemology behind it and then a second piece that will be the case studies and also talk about how LDA/topic modeling apply that way of thinking about texts. Let me know what you think! This is one I'm most anxious about losing people in.  So let me know what parts could use clarifying. Also if I'm you know. Wrong about things.

Instead of a tool for topic modeling, I'll expand on how topic modeling applies bags of words and works with reference to a case study or two. Then the exercises will be about taking a case study and asking people to interpret some results.

**Comment by sehorowitz** [comment]
ok, one question -- what do the words in black in the Prism version mean (organs and body)? are they where "murder" and "medicine" overlap?
also, i did some editing, trying to break thinks down for students a bit more and add some more stuff that i think is useful about topic modeling (that it doesn't rely on a predetermined set of topics that the user provides).

**Comment by walshbr** [comment]
Black words are ones there is a tie between the winners. So something was marked with both murder and medicine. Worth mentioning you think?

Cool! I'll check it out.

**Comment by sehorowitz** [comment]
yeah, maybe a quick mention!

**Comment by walshbr** [comment]
Looks good to me! Updated for black and grey text on prism.
