### ISSUE TITLE
Review Topic modeling case study

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#43]
Check it out. I used my own topic modeling project for the walk through. hopefully that's fine? i just don't have access to the materials for a C19 topic modeling project, so I was using what I had at hand. seemed like it wasn't worth building a corpus just for the purposes of this lesson.

**Comment by sehorowitz** [comment]
yeah, for sure! i think the case study works great. 

anyway, the article it looks good. again, i did some edits to break it down for the students a bit, but that's all.
