### ISSUE TITLE
Review sentiment analysis

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#48]
check out the first section of sentiment analysis. as always, add whatever you want. the second piece, as i have it planned out, will look at a few examples. the emoji sentiment bit as well as prism for sentiment analysis. i might also get just a tad more technical, referencing back to supervised classifiers to talk about how you have to train computers to tag sentiment.

**Comment by sehorowitz** [comment]
looks good! just did some minor edits!
