### ISSUE TITLE
New title

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#69]
To make it seem less all encompassing, maybe: 

Introduction to Text Analysis: A Coursebook

?

**Comment by walshbr** [comment]
@sehorowitz what do you think of "Intro to Text Analysis: A Coursebook"? Trying to think towards something that parses better on a CV as well as something that describes a little better what this thing is. Also towards an alternate domain, as well.

**Comment by sehorowitz** [comment]
love it! let's do it!

**Comment by walshbr** [comment]
Cool! I changed it.
