### ISSUE TITLE
Proof NINES and archives

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#72]

**Comment by sehorowitz** [comment]
ok, i reworked this and the NINES article a bit. let me know what you think. happy to revert it back if it doesn't make sense to you!

**Comment by walshbr** [comment]
I think this helped the TEI section a lot. I think the NINES section needs 1-2 more sentences of framing at the beginning now to solidify the transition. I can do that, though, and I'll take a look tomorrow.

**Comment by walshbr** [comment]
Eh maybe it's fine. "Do no harm" I'll say and just close this for now.
