### ISSUE TITLE
proof bag of words

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#85]
i expanded on the bit to get a bit into how bag of words let's you do sentence similarity. Hopefully it's not quite too far afield. It's a bit hand-wavy and gets away from topic modeling, but maybe still worth keeping in there in some capacity?  At any rate, let me know what you think. I can shorten it if you want!

**Comment by sehorowitz** [comment]
looks great! i think a really good explanation of the theory behind topic modeling.
